// Auto-generated. Do not edit!

// (in-package chess_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let Operation = require('./Operation.js');

//-----------------------------------------------------------

class StepGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.ops = null;
    }
    else {
      if (initObj.hasOwnProperty('ops')) {
        this.ops = initObj.ops
      }
      else {
        this.ops = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type StepGoal
    // Serialize message field [ops]
    // Serialize the length for message field [ops]
    bufferOffset = _serializer.uint32(obj.ops.length, buffer, bufferOffset);
    obj.ops.forEach((val) => {
      bufferOffset = Operation.serialize(val, buffer, bufferOffset);
    });
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type StepGoal
    let len;
    let data = new StepGoal(null);
    // Deserialize message field [ops]
    // Deserialize array length for message field [ops]
    len = _deserializer.uint32(buffer, bufferOffset);
    data.ops = new Array(len);
    for (let i = 0; i < len; ++i) {
      data.ops[i] = Operation.deserialize(buffer, bufferOffset)
    }
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 28 * object.ops.length;
    return length + 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'chess_msgs/StepGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '3be9cbb635e0b30a073919d65ae3caf2';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal definition
    Operation[] ops
    
    ================================================================================
    MSG: chess_msgs/Operation
    # operation type go = 0 ; capture = 1 ; wait = 2
    uint32 OPERATION_GO = 0      
    uint32 OPERATION_CAPTURE = 1
    uint32 OPERATION_WAIT = 2
    
    # position type far = 0; near = 1
    uint32 POSITION_FAR = 0
    uint32 POSITION_NEAR = 1
    
    uint32 type
    
    uint32  pick_type
    float32 pick_x
    float32 pick_y
    
    uint32  place_type
    float32 place_x
    float32 place_y
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new StepGoal(null);
    if (msg.ops !== undefined) {
      resolved.ops = new Array(msg.ops.length);
      for (let i = 0; i < resolved.ops.length; ++i) {
        resolved.ops[i] = Operation.Resolve(msg.ops[i]);
      }
    }
    else {
      resolved.ops = []
    }

    return resolved;
    }
};

module.exports = StepGoal;
