# chess board
has_board: true
board_id: "board"
# size
board_height: 0.31  
board_width: 0.31   
board_depth: 0.026
# position
board_p_x: 0.319887320396
board_p_y: -0.257076297461
board_p_z: 0.013

# orientation
board_o_x: 0
board_o_y: 0
board_o_z: -0.383
board_o_w: 0.924
