; Auto-generated. Do not edit!


(cl:in-package chess_gui-msg)


;//! \htmlinclude StepResult.msg.html

(cl:defclass <StepResult> (roslisp-msg-protocol:ros-message)
  ((res
    :reader res
    :initarg :res
    :type cl:boolean
    :initform cl:nil)
   (msg
    :reader msg
    :initarg :msg
    :type cl:string
    :initform ""))
)

(cl:defclass StepResult (<StepResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <StepResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'StepResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name chess_gui-msg:<StepResult> is deprecated: use chess_gui-msg:StepResult instead.")))

(cl:ensure-generic-function 'res-val :lambda-list '(m))
(cl:defmethod res-val ((m <StepResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader chess_gui-msg:res-val is deprecated.  Use chess_gui-msg:res instead.")
  (res m))

(cl:ensure-generic-function 'msg-val :lambda-list '(m))
(cl:defmethod msg-val ((m <StepResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader chess_gui-msg:msg-val is deprecated.  Use chess_gui-msg:msg instead.")
  (msg m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <StepResult>) ostream)
  "Serializes a message object of type '<StepResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'res) 1 0)) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'msg))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'msg))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <StepResult>) istream)
  "Deserializes a message object of type '<StepResult>"
    (cl:setf (cl:slot-value msg 'res) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'msg) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'msg) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<StepResult>)))
  "Returns string type for a message object of type '<StepResult>"
  "chess_gui/StepResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'StepResult)))
  "Returns string type for a message object of type 'StepResult"
  "chess_gui/StepResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<StepResult>)))
  "Returns md5sum for a message object of type '<StepResult>"
  "21744300052380276c040efd28f6660f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'StepResult)))
  "Returns md5sum for a message object of type 'StepResult"
  "21744300052380276c040efd28f6660f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<StepResult>)))
  "Returns full string definition for message of type '<StepResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%bool res~%string msg~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'StepResult)))
  "Returns full string definition for message of type 'StepResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result definition~%bool res~%string msg~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <StepResult>))
  (cl:+ 0
     1
     4 (cl:length (cl:slot-value msg 'msg))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <StepResult>))
  "Converts a ROS message object to a list"
  (cl:list 'StepResult
    (cl:cons ':res (res msg))
    (cl:cons ':msg (msg msg))
))
