// Generated by gencpp from file chess_msgs/PlayResponse.msg
// DO NOT EDIT!


#ifndef CHESS_MSGS_MESSAGE_PLAYRESPONSE_H
#define CHESS_MSGS_MESSAGE_PLAYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chess_msgs
{
template <class ContainerAllocator>
struct PlayResponse_
{
  typedef PlayResponse_<ContainerAllocator> Type;

  PlayResponse_()
    : res(false)
    , msg()  {
    }
  PlayResponse_(const ContainerAllocator& _alloc)
    : res(false)
    , msg(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _res_type;
  _res_type res;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _msg_type;
  _msg_type msg;




  typedef boost::shared_ptr< ::chess_msgs::PlayResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chess_msgs::PlayResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlayResponse_

typedef ::chess_msgs::PlayResponse_<std::allocator<void> > PlayResponse;

typedef boost::shared_ptr< ::chess_msgs::PlayResponse > PlayResponsePtr;
typedef boost::shared_ptr< ::chess_msgs::PlayResponse const> PlayResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chess_msgs::PlayResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chess_msgs::PlayResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chess_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'chess_msgs': ['/home/carson/chess_ws/src/chess_msgs/msg', '/home/carson/chess_ws/devel/share/chess_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chess_msgs::PlayResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chess_msgs::PlayResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chess_msgs::PlayResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chess_msgs::PlayResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess_msgs::PlayResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess_msgs::PlayResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chess_msgs::PlayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "21744300052380276c040efd28f6660f";
  }

  static const char* value(const ::chess_msgs::PlayResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2174430005238027ULL;
  static const uint64_t static_value2 = 0x6c040efd28f6660fULL;
};

template<class ContainerAllocator>
struct DataType< ::chess_msgs::PlayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chess_msgs/PlayResponse";
  }

  static const char* value(const ::chess_msgs::PlayResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chess_msgs::PlayResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool res\n\
string msg\n\
";
  }

  static const char* value(const ::chess_msgs::PlayResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chess_msgs::PlayResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlayResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chess_msgs::PlayResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chess_msgs::PlayResponse_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.res);
    s << indent << "msg: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHESS_MSGS_MESSAGE_PLAYRESPONSE_H
