// Generated by gencpp from file chess_msgs/PlayRequest.msg
// DO NOT EDIT!


#ifndef CHESS_MSGS_MESSAGE_PLAYREQUEST_H
#define CHESS_MSGS_MESSAGE_PLAYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <chess_msgs/Operation.h>

namespace chess_msgs
{
template <class ContainerAllocator>
struct PlayRequest_
{
  typedef PlayRequest_<ContainerAllocator> Type;

  PlayRequest_()
    : max_x(0.0)
    , max_y(0.0)
    , ops()  {
    }
  PlayRequest_(const ContainerAllocator& _alloc)
    : max_x(0.0)
    , max_y(0.0)
    , ops(_alloc)  {
  (void)_alloc;
    }



   typedef float _max_x_type;
  _max_x_type max_x;

   typedef float _max_y_type;
  _max_y_type max_y;

   typedef std::vector< ::chess_msgs::Operation_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::chess_msgs::Operation_<ContainerAllocator> >::other >  _ops_type;
  _ops_type ops;




  typedef boost::shared_ptr< ::chess_msgs::PlayRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chess_msgs::PlayRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PlayRequest_

typedef ::chess_msgs::PlayRequest_<std::allocator<void> > PlayRequest;

typedef boost::shared_ptr< ::chess_msgs::PlayRequest > PlayRequestPtr;
typedef boost::shared_ptr< ::chess_msgs::PlayRequest const> PlayRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chess_msgs::PlayRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chess_msgs::PlayRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chess_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'chess_msgs': ['/home/carson/chess_ws/src/chess_msgs/msg', '/home/carson/chess_ws/devel/share/chess_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chess_msgs::PlayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chess_msgs::PlayRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chess_msgs::PlayRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chess_msgs::PlayRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess_msgs::PlayRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess_msgs::PlayRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chess_msgs::PlayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0e5c4809f45bf914ed4eff2bc1a842b";
  }

  static const char* value(const ::chess_msgs::PlayRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0e5c4809f45bf91ULL;
  static const uint64_t static_value2 = 0x4ed4eff2bc1a842bULL;
};

template<class ContainerAllocator>
struct DataType< ::chess_msgs::PlayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chess_msgs/PlayRequest";
  }

  static const char* value(const ::chess_msgs::PlayRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chess_msgs::PlayRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float32 max_x\n\
float32 max_y\n\
Operation[] ops\n\
\n\
================================================================================\n\
MSG: chess_msgs/Operation\n\
# operation type go = 0 ; capture = 1 ; wait = 2\n\
uint32 OPERATION_GO = 0      \n\
uint32 OPERATION_CAPTURE = 1\n\
uint32 OPERATION_WAIT = 2\n\
\n\
# position type far = 0; near = 1\n\
uint32 POSITION_FAR = 0\n\
uint32 POSITION_NEAR = 1\n\
\n\
uint32 type\n\
\n\
uint32  pick_type\n\
float32 pick_x\n\
float32 pick_y\n\
\n\
uint32  place_type\n\
float32 place_x\n\
float32 place_y\n\
\n\
";
  }

  static const char* value(const ::chess_msgs::PlayRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chess_msgs::PlayRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.max_x);
      stream.next(m.max_y);
      stream.next(m.ops);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlayRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chess_msgs::PlayRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chess_msgs::PlayRequest_<ContainerAllocator>& v)
  {
    s << indent << "max_x: ";
    Printer<float>::stream(s, indent + "  ", v.max_x);
    s << indent << "max_y: ";
    Printer<float>::stream(s, indent + "  ", v.max_y);
    s << indent << "ops[]" << std::endl;
    for (size_t i = 0; i < v.ops.size(); ++i)
    {
      s << indent << "  ops[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::chess_msgs::Operation_<ContainerAllocator> >::stream(s, indent + "    ", v.ops[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHESS_MSGS_MESSAGE_PLAYREQUEST_H
