// Generated by gencpp from file chess_msgs/Point.msg
// DO NOT EDIT!


#ifndef CHESS_MSGS_MESSAGE_POINT_H
#define CHESS_MSGS_MESSAGE_POINT_H

#include <ros/service_traits.h>


#include <chess_msgs/PointRequest.h>
#include <chess_msgs/PointResponse.h>


namespace chess_msgs
{

struct Point
{

typedef PointRequest Request;
typedef PointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Point
} // namespace chess_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::chess_msgs::Point > {
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::chess_msgs::Point&) { return value(); }
};

template<>
struct DataType< ::chess_msgs::Point > {
  static const char* value()
  {
    return "chess_msgs/Point";
  }

  static const char* value(const ::chess_msgs::Point&) { return value(); }
};


// service_traits::MD5Sum< ::chess_msgs::PointRequest> should match 
// service_traits::MD5Sum< ::chess_msgs::Point > 
template<>
struct MD5Sum< ::chess_msgs::PointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::chess_msgs::Point >::value();
  }
  static const char* value(const ::chess_msgs::PointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::chess_msgs::PointRequest> should match 
// service_traits::DataType< ::chess_msgs::Point > 
template<>
struct DataType< ::chess_msgs::PointRequest>
{
  static const char* value()
  {
    return DataType< ::chess_msgs::Point >::value();
  }
  static const char* value(const ::chess_msgs::PointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::chess_msgs::PointResponse> should match 
// service_traits::MD5Sum< ::chess_msgs::Point > 
template<>
struct MD5Sum< ::chess_msgs::PointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::chess_msgs::Point >::value();
  }
  static const char* value(const ::chess_msgs::PointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::chess_msgs::PointResponse> should match 
// service_traits::DataType< ::chess_msgs::Point > 
template<>
struct DataType< ::chess_msgs::PointResponse>
{
  static const char* value()
  {
    return DataType< ::chess_msgs::Point >::value();
  }
  static const char* value(const ::chess_msgs::PointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHESS_MSGS_MESSAGE_POINT_H
