// Generated by gencpp from file chess_msgs/StepFeedback.msg
// DO NOT EDIT!


#ifndef CHESS_MSGS_MESSAGE_STEPFEEDBACK_H
#define CHESS_MSGS_MESSAGE_STEPFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chess_msgs
{
template <class ContainerAllocator>
struct StepFeedback_
{
  typedef StepFeedback_<ContainerAllocator> Type;

  StepFeedback_()
    : feedback()  {
    }
  StepFeedback_(const ContainerAllocator& _alloc)
    : feedback(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _feedback_type;
  _feedback_type feedback;




  typedef boost::shared_ptr< ::chess_msgs::StepFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chess_msgs::StepFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct StepFeedback_

typedef ::chess_msgs::StepFeedback_<std::allocator<void> > StepFeedback;

typedef boost::shared_ptr< ::chess_msgs::StepFeedback > StepFeedbackPtr;
typedef boost::shared_ptr< ::chess_msgs::StepFeedback const> StepFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chess_msgs::StepFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chess_msgs::StepFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chess_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'chess_msgs': ['/home/carson/chess_ws/src/chess_msgs/msg', '/home/carson/chess_ws/devel/share/chess_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chess_msgs::StepFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chess_msgs::StepFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chess_msgs::StepFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chess_msgs::StepFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess_msgs::StepFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess_msgs::StepFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chess_msgs::StepFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c14cdf907e5c7c7fd47292add15660f0";
  }

  static const char* value(const ::chess_msgs::StepFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc14cdf907e5c7c7fULL;
  static const uint64_t static_value2 = 0xd47292add15660f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::chess_msgs::StepFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chess_msgs/StepFeedback";
  }

  static const char* value(const ::chess_msgs::StepFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chess_msgs::StepFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# feedback definition\n\
string feedback\n\
";
  }

  static const char* value(const ::chess_msgs::StepFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chess_msgs::StepFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StepFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chess_msgs::StepFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chess_msgs::StepFeedback_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHESS_MSGS_MESSAGE_STEPFEEDBACK_H
