// Generated by gencpp from file chess_msgs/StepActionGoal.msg
// DO NOT EDIT!


#ifndef CHESS_MSGS_MESSAGE_STEPACTIONGOAL_H
#define CHESS_MSGS_MESSAGE_STEPACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <chess_msgs/StepGoal.h>

namespace chess_msgs
{
template <class ContainerAllocator>
struct StepActionGoal_
{
  typedef StepActionGoal_<ContainerAllocator> Type;

  StepActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  StepActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::chess_msgs::StepGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::chess_msgs::StepActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chess_msgs::StepActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct StepActionGoal_

typedef ::chess_msgs::StepActionGoal_<std::allocator<void> > StepActionGoal;

typedef boost::shared_ptr< ::chess_msgs::StepActionGoal > StepActionGoalPtr;
typedef boost::shared_ptr< ::chess_msgs::StepActionGoal const> StepActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chess_msgs::StepActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chess_msgs::StepActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace chess_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'chess_msgs': ['/home/carson/chess_ws/src/chess_msgs/msg', '/home/carson/chess_ws/devel/share/chess_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::chess_msgs::StepActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chess_msgs::StepActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chess_msgs::StepActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chess_msgs::StepActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess_msgs::StepActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chess_msgs::StepActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chess_msgs::StepActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39ea5d0a689a1407a71b7f6e3e65a984";
  }

  static const char* value(const ::chess_msgs::StepActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39ea5d0a689a1407ULL;
  static const uint64_t static_value2 = 0xa71b7f6e3e65a984ULL;
};

template<class ContainerAllocator>
struct DataType< ::chess_msgs::StepActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chess_msgs/StepActionGoal";
  }

  static const char* value(const ::chess_msgs::StepActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chess_msgs::StepActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
StepGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: chess_msgs/StepGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# goal definition\n\
Operation[] ops\n\
\n\
================================================================================\n\
MSG: chess_msgs/Operation\n\
# operation type go = 0 ; capture = 1 ; wait = 2\n\
uint32 OPERATION_GO = 0      \n\
uint32 OPERATION_CAPTURE = 1\n\
uint32 OPERATION_WAIT = 2\n\
\n\
# position type far = 0; near = 1\n\
uint32 POSITION_FAR = 0\n\
uint32 POSITION_NEAR = 1\n\
\n\
uint32 type\n\
\n\
uint32  pick_type\n\
float32 pick_x\n\
float32 pick_y\n\
\n\
uint32  place_type\n\
float32 place_x\n\
float32 place_y\n\
\n\
";
  }

  static const char* value(const ::chess_msgs::StepActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chess_msgs::StepActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StepActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chess_msgs::StepActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chess_msgs::StepActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::chess_msgs::StepGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHESS_MSGS_MESSAGE_STEPACTIONGOAL_H
