# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from chess_gui/StepGoal.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import chess_gui.msg

class StepGoal(genpy.Message):
  _md5sum = "8659c0f3910f1e3a2a4f3f1f180fafca"
  _type = "chess_gui/StepGoal"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
# goal definition
float32 max_x
float32 max_y
Operation[] ops

================================================================================
MSG: chess_gui/Operation
# operation type go = 0 ; capture = 1
uint32 OPERATION_GO = 0      
uint32 OPREATION_CAPTURE = 1

uint32 type

float32 pick_x
float32 pick_y

float32 place_x
float32 place_y

"""
  __slots__ = ['max_x','max_y','ops']
  _slot_types = ['float32','float32','chess_gui/Operation[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       max_x,max_y,ops

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(StepGoal, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.max_x is None:
        self.max_x = 0.
      if self.max_y is None:
        self.max_y = 0.
      if self.ops is None:
        self.ops = []
    else:
      self.max_x = 0.
      self.max_y = 0.
      self.ops = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2f().pack(_x.max_x, _x.max_y))
      length = len(self.ops)
      buff.write(_struct_I.pack(length))
      for val1 in self.ops:
        _x = val1
        buff.write(_get_struct_I4f().pack(_x.type, _x.pick_x, _x.pick_y, _x.place_x, _x.place_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.ops is None:
        self.ops = None
      end = 0
      _x = self
      start = end
      end += 8
      (_x.max_x, _x.max_y,) = _get_struct_2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ops = []
      for i in range(0, length):
        val1 = chess_gui.msg.Operation()
        _x = val1
        start = end
        end += 20
        (_x.type, _x.pick_x, _x.pick_y, _x.place_x, _x.place_y,) = _get_struct_I4f().unpack(str[start:end])
        self.ops.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2f().pack(_x.max_x, _x.max_y))
      length = len(self.ops)
      buff.write(_struct_I.pack(length))
      for val1 in self.ops:
        _x = val1
        buff.write(_get_struct_I4f().pack(_x.type, _x.pick_x, _x.pick_y, _x.place_x, _x.place_y))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.ops is None:
        self.ops = None
      end = 0
      _x = self
      start = end
      end += 8
      (_x.max_x, _x.max_y,) = _get_struct_2f().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.ops = []
      for i in range(0, length):
        val1 = chess_gui.msg.Operation()
        _x = val1
        start = end
        end += 20
        (_x.type, _x.pick_x, _x.pick_y, _x.place_x, _x.place_y,) = _get_struct_I4f().unpack(str[start:end])
        self.ops.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_I4f = None
def _get_struct_I4f():
    global _struct_I4f
    if _struct_I4f is None:
        _struct_I4f = struct.Struct("<I4f")
    return _struct_I4f
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
