// Auto-generated. Do not edit!

// (in-package chess_gui.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let Operation = require('./Operation.js');

//-----------------------------------------------------------

class StepGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.max_x = null;
      this.max_y = null;
      this.ops = null;
    }
    else {
      if (initObj.hasOwnProperty('max_x')) {
        this.max_x = initObj.max_x
      }
      else {
        this.max_x = 0.0;
      }
      if (initObj.hasOwnProperty('max_y')) {
        this.max_y = initObj.max_y
      }
      else {
        this.max_y = 0.0;
      }
      if (initObj.hasOwnProperty('ops')) {
        this.ops = initObj.ops
      }
      else {
        this.ops = [];
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type StepGoal
    // Serialize message field [max_x]
    bufferOffset = _serializer.float32(obj.max_x, buffer, bufferOffset);
    // Serialize message field [max_y]
    bufferOffset = _serializer.float32(obj.max_y, buffer, bufferOffset);
    // Serialize message field [ops]
    // Serialize the length for message field [ops]
    bufferOffset = _serializer.uint32(obj.ops.length, buffer, bufferOffset);
    obj.ops.forEach((val) => {
      bufferOffset = Operation.serialize(val, buffer, bufferOffset);
    });
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type StepGoal
    let len;
    let data = new StepGoal(null);
    // Deserialize message field [max_x]
    data.max_x = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [max_y]
    data.max_y = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [ops]
    // Deserialize array length for message field [ops]
    len = _deserializer.uint32(buffer, bufferOffset);
    data.ops = new Array(len);
    for (let i = 0; i < len; ++i) {
      data.ops[i] = Operation.deserialize(buffer, bufferOffset)
    }
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += 20 * object.ops.length;
    return length + 12;
  }

  static datatype() {
    // Returns string type for a message object
    return 'chess_gui/StepGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '8659c0f3910f1e3a2a4f3f1f180fafca';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal definition
    float32 max_x
    float32 max_y
    Operation[] ops
    
    ================================================================================
    MSG: chess_gui/Operation
    # operation type go = 0 ; capture = 1
    uint32 OPERATION_GO = 0      
    uint32 OPREATION_CAPTURE = 1
    
    uint32 type
    
    float32 pick_x
    float32 pick_y
    
    float32 place_x
    float32 place_y
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new StepGoal(null);
    if (msg.max_x !== undefined) {
      resolved.max_x = msg.max_x;
    }
    else {
      resolved.max_x = 0.0
    }

    if (msg.max_y !== undefined) {
      resolved.max_y = msg.max_y;
    }
    else {
      resolved.max_y = 0.0
    }

    if (msg.ops !== undefined) {
      resolved.ops = new Array(msg.ops.length);
      for (let i = 0; i < resolved.ops.length; ++i) {
        resolved.ops[i] = Operation.Resolve(msg.ops[i]);
      }
    }
    else {
      resolved.ops = []
    }

    return resolved;
    }
};

module.exports = StepGoal;
