(cl:defpackage chess_msgs-msg
  (:use )
  (:export
   "<MOVE>"
   "MOVE"
   "<OPERATION>"
   "OPERATION"
   "<RESULT>"
   "RESULT"
   "<STEPACTION>"
   "STEPACTION"
   "<STEPACTIONFEEDBACK>"
   "STEPACTIONFEEDBACK"
   "<STEPACTIONGOAL>"
   "STEPACTIONGOAL"
   "<STEPACTIONRESULT>"
   "STEPACTIONRESULT"
   "<STEPFEEDBACK>"
   "STEPFEEDBACK"
   "<STEPGOAL>"
   "STEPGOAL"
   "<STEPRESULT>"
   "STEPRESULT"
   "<ZPOSE>"
   "ZPOSE"
  ))

